---
- name: Install and Configure pvt DNS Bind9 server.
  hosts: [vikimanaged]
  become: true
  become_user: root
  remote_user: vagrant
  gather_facts: false
  
  vars:
    domain: vikilabs.local
    # Network portion of IP has to be in reverse order. Read on internet for more details.
    # 10.10.10.0/8 Subnet in this case
    rev_domain: 10.10.10.in-addr.arpa 
  
  tasks:
    - name: Install bind9
      apt: name=bind9 state=present

    - name: Set hostname
      hostname:
        name: "{{ host_name }}"

    - name: Set hostname fact
      set_fact:
        ansible_fqdn: "{{ host_name }}"

    - name: Copy bind9 default config
      template:
        src: templates/default.bind9.j2
        dest: /etc/default/bind9

    - name: Copy named conf options file
      template:
        src: templates/named.conf.options.master.j2
        dest: /etc/bind/named.conf.options
      when:
        - ansible_dns_role == 'master'

    - name: Copy named conf local file
      template:
        src: templates/named.conf.local.master.j2
        dest: /etc/bind/named.conf.local
      when:
        - ansible_dns_role == 'master'

    - name: Make zones Directory
      file:
        path: /etc/bind/zones
        state: directory
        owner: root
        mode: 0750

    - name: Copy forward file
      template:
        src: templates/db.forward.master.j2
        dest: /etc/bind/zones/db.{{ domain }}
        owner: root
        mode: 0640
      when:
        - ansible_dns_role == 'master'
    
    - name: Copy reverse file
      template:
        src: templates/db.reverse.master.j2
        dest: /etc/bind/zones/db.{{ rev_domain }}
        owner: root
        mode: 0640
      when:
        - ansible_dns_role == 'master'
    
    - name: Copy named conf options file
      template:
        src: templates/named.conf.options.master.j2
        dest: /etc/bind/named.conf.options
      when:
        - ansible_dns_role == 'master'

    - name: Copy named conf local file
      template:
        src: templates/named.conf.local.master.j2
        dest: /etc/bind/named.conf.local
      when:
        - ansible_dns_role == 'master'

    - name: Copy named conf options file
      template:
        src: templates/named.conf.options.slave.j2
        dest: /etc/bind/named.conf.options
      when:
        - ansible_dns_role == 'slave'

    - name: Copy named conf local file
      template:
        src: templates/named.conf.local.slave.j2
        dest: /etc/bind/named.conf.local
      when:
        - ansible_dns_role == 'slave'

    - name: restart bind9
      service:
        name: bind9
        state: restarted
    
